# Generated by Django 4.2.14 on 2024-07-25 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0002_fantasyteamstats_is_current_season'),
    ]

    operations = [
        migrations.CreateModel(
            name='NFLTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('abbreviation', models.CharField(max_length=3, unique=True)),
                ('conference', models.CharField(max_length=3)),
                ('division', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'nfl_teams',
            },
        ),
        migrations.CreateModel(
            name='LeagueScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scoring_type', models.CharField(choices=[('passing', 'Passing'), ('rushing', 'Rushing'), ('receiving', 'Receiving'), ('defense', 'Def'), ('misc', 'Misc'), ('kicking', 'Kicking')], max_length=50)),
                ('stat_name', models.CharField(max_length=50)),
                ('point_value', models.FloatField(default=0.0)),
                ('league_settings', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ffl_companion.leaguesettings')),
            ],
            options={
                'db_table': 'league_scoring',
                'unique_together': {('scoring_type', 'stat_name', 'league_settings_id')},
            },
        ),
    ]
