# Generated by Django 4.2.14 on 2024-07-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0004_nflteam_season_year_alter_nflteam_abbreviation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nflteam',
            name='abbreviation',
            field=models.CharField(choices=[('ARI', 'Ari'), ('ATL', 'Atl'), ('BAL', 'Bal'), ('BUF', 'Buf'), ('CAR', 'Car'), ('CHI', 'Chi'), ('CIN', 'Cin'), ('CLE', 'Cle'), ('DAL', 'Dal'), ('DEN', 'Den'), ('DET', 'Det'), ('GB', 'Gb'), ('HOU', 'Hou'), ('IND', 'Ind'), ('JAX', 'Jax'), ('KC', 'Kc'), ('MIA', 'Mia'), ('MIN', 'Min'), ('NE', 'Ne'), ('NO', 'No'), ('NYG', 'Nyg'), ('NYJ', 'Nyj'), ('LV', 'Lv'), ('PHI', 'Phi'), ('PIT', 'Pit'), ('LAC', 'Lac'), ('SF', 'Sf'), ('SEA', 'Sea'), ('LAR', 'Lar'), ('TB', 'Tb'), ('TEN', 'Ten'), ('WAS', 'Was')], max_length=3),
        ),
        migrations.AlterUniqueTogether(
            name='nflteam',
            unique_together={('abbreviation', 'season_year')},
        ),
    ]
