# Generated by Django 4.2.14 on 2024-07-25 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0006_alter_leaguescoring_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatsweekly',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats_weekly', to='ffl_companion.player'),
        ),
    ]
