# Generated by Django 4.2.14 on 2024-07-25 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0007_alter_playerstatsweekly_player'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaguesettings',
            name='scoring',
        ),
        migrations.AddField(
            model_name='leaguescoring',
            name='league_settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scoring', to='ffl_companion.leaguesettings'),
        ),
    ]
