# Generated by Django 4.2.14 on 2024-07-25 20:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0008_remove_leaguesettings_scoring_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Qb'), ('WR', 'Wr'), ('RB', 'Rb'), ('FB', 'Fb'), ('TE', 'Te'), ('DEF', 'Def'), ('K', 'K')], max_length=3),
        ),
        migrations.AlterField(
            model_name='playerstatsweekly',
            name='game_week',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(18)]),
        ),
    ]
