# Generated by Django 4.2.14 on 2024-07-26 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0009_alter_player_position_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatsweekly',
            name='season_start_year',
            field=models.IntegerField(db_index=True, default=2024),
        ),
    ]
