# Generated by Django 4.2.14 on 2024-07-26 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0010_alter_playerstatsweekly_season_start_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerstatsweekly',
            name='day_of_week',
            field=models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('Thu', 'Thu'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('Sun', 'Sun')], default='Sun', max_length=9),
        ),
    ]
