# Generated by Django 4.2.14 on 2024-07-26 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0011_alter_playerstatsweekly_day_of_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.IntegerField(default=0)),
                ('trade_date', models.DateField(null=True)),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='ffl_companion.leaguesettings')),
                ('owners', models.ManyToManyField(related_name='owner_trades', to='ffl_companion.teamowner')),
                ('players', models.ManyToManyField(related_name='player_trades', to='ffl_companion.player')),
            ],
            options={
                'db_table': 'trades',
            },
        ),
    ]
