# Generated by Django 4.2.14 on 2024-07-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0013_remove_trade_owners_remove_trade_players_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='league_host',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaguesettings',
            name='league_host_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaguesettings',
            name='league_id',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
