# Generated by Django 4.2.14 on 2024-07-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0014_leaguesettings_league_host_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamowner',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='teamowner',
            name='password',
            field=models.CharField(default='password', max_length=128, verbose_name='password'),
        ),
    ]
