# Generated by Django 4.2.14 on 2024-08-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0018_leaguescoring_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teamowner',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
