# Generated by Django 4.2.14 on 2024-08-13 13:08

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ffl_companion', '0020_fantasyteamstats_owner_nflplayer_owner_roster_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nflplayer',
            name='fantasy_team',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='owner_one',
        ),
        migrations.RemoveField(
            model_name='trade',
            name='owner_two',
        ),
        migrations.AlterUniqueTogether(
            name='fantasyteamstats',
            unique_together={('owner', 'season_start_year')},
        ),
        migrations.AlterUniqueTogether(
            name='roster',
            unique_together={('owner', 'roster_year')},
        ),
        migrations.RemoveField(
            model_name='fantasyteamstats',
            name='team_owner',
        ),
        migrations.RemoveField(
            model_name='roster',
            name='team_owner',
        ),
    ]
