# Generated by Django 4.2.14 on 2024-08-13 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0021_remove_nflplayer_fantasy_team_remove_trade_owner_one_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamOwner',
        ),
    ]
