# Generated by Django 4.2.14 on 2024-08-13 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ffl_companion', '0022_delete_teamowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='rosters',
        ),
        migrations.AddField(
            model_name='roster',
            name='players',
            field=models.ManyToManyField(related_name='player_rosters', to='ffl_companion.player'),
        ),
    ]
