# Generated by Django 4.2.14 on 2024-08-16 13:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ffl_companion', '0023_remove_player_rosters_roster_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaguesettings',
            name='lineup_positions',
            field=models.CharField(help_text='comma separated list of starting positions and bench spots', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='leaguesettings',
            name='player_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leaguesettings',
            name='starter_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('QB', 'Qb'), ('WR', 'Wr'), ('RB', 'Rb'), ('FB', 'Fb'), ('TE', 'Te'), ('DEF', 'Def'), ('K', 'K'), ('FLEX', 'Flex')], max_length=4),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('alert', 'Alert'), ('user', 'User')], max_length=255)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notifications',
            },
        ),
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataset', models.CharField(blank=True, max_length=255, null=True)),
                ('week', models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(18)])),
                ('bench', models.ManyToManyField(related_name='bench_players', to='ffl_companion.player')),
                ('roster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineups', to='ffl_companion.roster')),
                ('starters', models.ManyToManyField(related_name='starters', to='ffl_companion.player')),
            ],
            options={
                'db_table': 'lineups',
                'unique_together': {('roster', 'week')},
            },
        ),
    ]
